module.exports {
    products:[
        {
            _id: '1',
            name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
            category: 'Shirts',
            image: '/images/product-2.jpg',
            price: 70,
            brand: 'Nike',
            rating: 45,
            numReviews: 51,
        },
        {
            _id: '3',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image: '/images/product-3.jpg',
            price: 59,
            brand: 'Hiskywin',
            rating: 4.,
            numReviews: 45,
        },
        {
            _id: '4',
            name: 'Under Armour Mens Sportsyle Tricot Joggers',
            category: 'Shirts',
            image: '/images/product-4.jpg',
            price: 90,
            brand: 'Hiskywin',
            rating: 2.5,
            numReviews: 198,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Champion Mens Graphis Powerblend Fleece Jogger',
            category: 'Pants',
            image: '/images/product-5.jpg',
            price: 119,
            brand: 'Hiskywin',
            rating: 3.5,
            numReviews: 89,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
            category: 'Pants',
            image: '/images/product-6.jpg',
            price: 85,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 45,
            countInStock: 6,
        },
    ],
};